// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.20.3
// source: launchy.proto

package launchy_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StopSignal int32

const (
	StopSignal_UnspecifiedSS StopSignal = 0
	StopSignal_Interupt      StopSignal = 1
	StopSignal_Kill          StopSignal = 2
)

// Enum value maps for StopSignal.
var (
	StopSignal_name = map[int32]string{
		0: "UnspecifiedSS",
		1: "Interupt",
		2: "Kill",
	}
	StopSignal_value = map[string]int32{
		"UnspecifiedSS": 0,
		"Interupt":      1,
		"Kill":          2,
	}
)

func (x StopSignal) Enum() *StopSignal {
	p := new(StopSignal)
	*p = x
	return p
}

func (x StopSignal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StopSignal) Descriptor() protoreflect.EnumDescriptor {
	return file_launchy_proto_enumTypes[0].Descriptor()
}

func (StopSignal) Type() protoreflect.EnumType {
	return &file_launchy_proto_enumTypes[0]
}

func (x StopSignal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StopSignal.Descriptor instead.
func (StopSignal) EnumDescriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{0}
}

type ProcessState int32

const (
	ProcessState_UnspecifiedPS ProcessState = 0
	ProcessState_Starting      ProcessState = 1
	ProcessState_Running       ProcessState = 2
	ProcessState_Stopping      ProcessState = 3
	ProcessState_Stopped       ProcessState = 4
)

// Enum value maps for ProcessState.
var (
	ProcessState_name = map[int32]string{
		0: "UnspecifiedPS",
		1: "Starting",
		2: "Running",
		3: "Stopping",
		4: "Stopped",
	}
	ProcessState_value = map[string]int32{
		"UnspecifiedPS": 0,
		"Starting":      1,
		"Running":       2,
		"Stopping":      3,
		"Stopped":       4,
	}
)

func (x ProcessState) Enum() *ProcessState {
	p := new(ProcessState)
	*p = x
	return p
}

func (x ProcessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessState) Descriptor() protoreflect.EnumDescriptor {
	return file_launchy_proto_enumTypes[1].Descriptor()
}

func (ProcessState) Type() protoreflect.EnumType {
	return &file_launchy_proto_enumTypes[1]
}

func (x ProcessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessState.Descriptor instead.
func (ProcessState) EnumDescriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{1}
}

type SystemdAction int32

const (
	SystemdAction_UnspecifiedSA SystemdAction = 0
	SystemdAction_Stop          SystemdAction = 1
	SystemdAction_Start         SystemdAction = 2
	SystemdAction_Restart       SystemdAction = 3
	SystemdAction_Cat           SystemdAction = 4
	SystemdAction_Status        SystemdAction = 5
)

// Enum value maps for SystemdAction.
var (
	SystemdAction_name = map[int32]string{
		0: "UnspecifiedSA",
		1: "Stop",
		2: "Start",
		3: "Restart",
		4: "Cat",
		5: "Status",
	}
	SystemdAction_value = map[string]int32{
		"UnspecifiedSA": 0,
		"Stop":          1,
		"Start":         2,
		"Restart":       3,
		"Cat":           4,
		"Status":        5,
	}
)

func (x SystemdAction) Enum() *SystemdAction {
	p := new(SystemdAction)
	*p = x
	return p
}

func (x SystemdAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemdAction) Descriptor() protoreflect.EnumDescriptor {
	return file_launchy_proto_enumTypes[2].Descriptor()
}

func (SystemdAction) Type() protoreflect.EnumType {
	return &file_launchy_proto_enumTypes[2]
}

func (x SystemdAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemdAction.Descriptor instead.
func (SystemdAction) EnumDescriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{2}
}

type RestartProcessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signal StopSignal `protobuf:"varint,1,opt,name=signal,proto3,enum=launchy_proto.StopSignal" json:"signal,omitempty"`
}

func (x *RestartProcessRequest) Reset() {
	*x = RestartProcessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launchy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestartProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartProcessRequest) ProtoMessage() {}

func (x *RestartProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launchy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartProcessRequest.ProtoReflect.Descriptor instead.
func (*RestartProcessRequest) Descriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{0}
}

func (x *RestartProcessRequest) GetSignal() StopSignal {
	if x != nil {
		return x.Signal
	}
	return StopSignal_UnspecifiedSS
}

type RestartProcessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RestartProcessResponse) Reset() {
	*x = RestartProcessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launchy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestartProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartProcessResponse) ProtoMessage() {}

func (x *RestartProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launchy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartProcessResponse.ProtoReflect.Descriptor instead.
func (*RestartProcessResponse) Descriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{1}
}

type StopProcessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signal StopSignal `protobuf:"varint,1,opt,name=signal,proto3,enum=launchy_proto.StopSignal" json:"signal,omitempty"`
}

func (x *StopProcessRequest) Reset() {
	*x = StopProcessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launchy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProcessRequest) ProtoMessage() {}

func (x *StopProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launchy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProcessRequest.ProtoReflect.Descriptor instead.
func (*StopProcessRequest) Descriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{2}
}

func (x *StopProcessRequest) GetSignal() StopSignal {
	if x != nil {
		return x.Signal
	}
	return StopSignal_UnspecifiedSS
}

type StopProcessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopProcessResponse) Reset() {
	*x = StopProcessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launchy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProcessResponse) ProtoMessage() {}

func (x *StopProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launchy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProcessResponse.ProtoReflect.Descriptor instead.
func (*StopProcessResponse) Descriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{3}
}

type ProcessStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProcessStatusRequest) Reset() {
	*x = ProcessStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launchy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStatusRequest) ProtoMessage() {}

func (x *ProcessStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launchy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStatusRequest.ProtoReflect.Descriptor instead.
func (*ProcessStatusRequest) Descriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{4}
}

type ProcessStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *ProcessStatusResponse) Reset() {
	*x = ProcessStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launchy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStatusResponse) ProtoMessage() {}

func (x *ProcessStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launchy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStatusResponse.ProtoReflect.Descriptor instead.
func (*ProcessStatusResponse) Descriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type StartProcessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartProcessRequest) Reset() {
	*x = StartProcessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launchy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessRequest) ProtoMessage() {}

func (x *StartProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launchy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessRequest.ProtoReflect.Descriptor instead.
func (*StartProcessRequest) Descriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{6}
}

type StartProcessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartProcessResponse) Reset() {
	*x = StartProcessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launchy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessResponse) ProtoMessage() {}

func (x *StartProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launchy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessResponse.ProtoReflect.Descriptor instead.
func (*StartProcessResponse) Descriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{7}
}

type StopLaunchyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// signal to use to stop the process/command if it is running
	StopCommandSignal StopSignal `protobuf:"varint,1,opt,name=stopCommandSignal,proto3,enum=launchy_proto.StopSignal" json:"stopCommandSignal,omitempty"`
}

func (x *StopLaunchyRequest) Reset() {
	*x = StopLaunchyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launchy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopLaunchyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopLaunchyRequest) ProtoMessage() {}

func (x *StopLaunchyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launchy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopLaunchyRequest.ProtoReflect.Descriptor instead.
func (*StopLaunchyRequest) Descriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{8}
}

func (x *StopLaunchyRequest) GetStopCommandSignal() StopSignal {
	if x != nil {
		return x.StopCommandSignal
	}
	return StopSignal_UnspecifiedSS
}

type StopLaunchyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopLaunchyResponse) Reset() {
	*x = StopLaunchyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launchy_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopLaunchyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopLaunchyResponse) ProtoMessage() {}

func (x *StopLaunchyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launchy_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopLaunchyResponse.ProtoReflect.Descriptor instead.
func (*StopLaunchyResponse) Descriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{9}
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launchy_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launchy_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{10}
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launchy_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launchy_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{11}
}

type ListSystemdServicesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSystemdServicesRequest) Reset() {
	*x = ListSystemdServicesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launchy_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSystemdServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSystemdServicesRequest) ProtoMessage() {}

func (x *ListSystemdServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launchy_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSystemdServicesRequest.ProtoReflect.Descriptor instead.
func (*ListSystemdServicesRequest) Descriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{12}
}

type ListSystemdServicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Services     []*SystemdUnitInfo `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	ErrorMessage string             `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	ErrorOutput  string             `protobuf:"bytes,3,opt,name=errorOutput,proto3" json:"errorOutput,omitempty"`
}

func (x *ListSystemdServicesResponse) Reset() {
	*x = ListSystemdServicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launchy_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSystemdServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSystemdServicesResponse) ProtoMessage() {}

func (x *ListSystemdServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launchy_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSystemdServicesResponse.ProtoReflect.Descriptor instead.
func (*ListSystemdServicesResponse) Descriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{13}
}

func (x *ListSystemdServicesResponse) GetServices() []*SystemdUnitInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ListSystemdServicesResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ListSystemdServicesResponse) GetErrorOutput() string {
	if x != nil {
		return x.ErrorOutput
	}
	return ""
}

type SystemdUnitInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unit        string `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Load        string `protobuf:"bytes,2,opt,name=load,proto3" json:"load,omitempty"`
	Active      string `protobuf:"bytes,3,opt,name=active,proto3" json:"active,omitempty"`
	Sub         string `protobuf:"bytes,4,opt,name=sub,proto3" json:"sub,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *SystemdUnitInfo) Reset() {
	*x = SystemdUnitInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launchy_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemdUnitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemdUnitInfo) ProtoMessage() {}

func (x *SystemdUnitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_launchy_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemdUnitInfo.ProtoReflect.Descriptor instead.
func (*SystemdUnitInfo) Descriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{14}
}

func (x *SystemdUnitInfo) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *SystemdUnitInfo) GetLoad() string {
	if x != nil {
		return x.Load
	}
	return ""
}

func (x *SystemdUnitInfo) GetActive() string {
	if x != nil {
		return x.Active
	}
	return ""
}

func (x *SystemdUnitInfo) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *SystemdUnitInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SystemdServiceActionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string        `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Action      SystemdAction `protobuf:"varint,2,opt,name=action,proto3,enum=launchy_proto.SystemdAction" json:"action,omitempty"`
}

func (x *SystemdServiceActionRequest) Reset() {
	*x = SystemdServiceActionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launchy_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemdServiceActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemdServiceActionRequest) ProtoMessage() {}

func (x *SystemdServiceActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launchy_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemdServiceActionRequest.ProtoReflect.Descriptor instead.
func (*SystemdServiceActionRequest) Descriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{15}
}

func (x *SystemdServiceActionRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SystemdServiceActionRequest) GetAction() SystemdAction {
	if x != nil {
		return x.Action
	}
	return SystemdAction_UnspecifiedSA
}

type SystemdServiceActionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandOutput string `protobuf:"bytes,1,opt,name=commandOutput,proto3" json:"commandOutput,omitempty"`
	ErrorMessage  string `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
}

func (x *SystemdServiceActionResponse) Reset() {
	*x = SystemdServiceActionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launchy_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemdServiceActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemdServiceActionResponse) ProtoMessage() {}

func (x *SystemdServiceActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launchy_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemdServiceActionResponse.ProtoReflect.Descriptor instead.
func (*SystemdServiceActionResponse) Descriptor() ([]byte, []int) {
	return file_launchy_proto_rawDescGZIP(), []int{16}
}

func (x *SystemdServiceActionResponse) GetCommandOutput() string {
	if x != nil {
		return x.CommandOutput
	}
	return ""
}

func (x *SystemdServiceActionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_launchy_proto protoreflect.FileDescriptor

var file_launchy_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a,
	0x0a, 0x15, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68,
	0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x6c, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x22, 0x18, 0x0a, 0x16, 0x52, 0x65,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x47, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6c, 0x61, 0x75,
	0x6e, 0x63, 0x68, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x22, 0x15, 0x0a,
	0x13, 0x53, 0x74, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2d, 0x0a, 0x15,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5d, 0x0a, 0x12, 0x53, 0x74,
	0x6f, 0x70, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x47, 0x0a, 0x11, 0x73, 0x74, 0x6f, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6c, 0x61,
	0x75, 0x6e, 0x63, 0x68, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x70,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x11, 0x73, 0x74, 0x6f, 0x70, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x74, 0x6f,
	0x70, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x0e, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x1c, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x64, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x9f, 0x01,
	0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x64, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22,
	0x85, 0x01, 0x0a, 0x0f, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x75, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x75, 0x62, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x75, 0x0a, 0x1b, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x6c, 0x61, 0x75, 0x6e, 0x63,
	0x68, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x64,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x68,
	0x0a, 0x1c, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24,
	0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x37, 0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x70,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x6e, 0x73, 0x70, 0x65, 0x63,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x75, 0x70, 0x74, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4b, 0x69, 0x6c, 0x6c, 0x10,
	0x02, 0x2a, 0x57, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x50, 0x53, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x67,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12,
	0x0c, 0x0a, 0x08, 0x53, 0x74, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x10, 0x03, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x10, 0x04, 0x2a, 0x59, 0x0a, 0x0d, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x11, 0x0a, 0x0d, 0x55,
	0x6e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x53, 0x41, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x10, 0x03,
	0x12, 0x07, 0x0a, 0x03, 0x43, 0x61, 0x74, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x10, 0x05, 0x42, 0x19, 0x5a, 0x17, 0x61, 0x63, 0x63, 0x75, 0x72, 0x38, 0x2e,
	0x69, 0x6f, 0x2f, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_launchy_proto_rawDescOnce sync.Once
	file_launchy_proto_rawDescData = file_launchy_proto_rawDesc
)

func file_launchy_proto_rawDescGZIP() []byte {
	file_launchy_proto_rawDescOnce.Do(func() {
		file_launchy_proto_rawDescData = protoimpl.X.CompressGZIP(file_launchy_proto_rawDescData)
	})
	return file_launchy_proto_rawDescData
}

var file_launchy_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_launchy_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_launchy_proto_goTypes = []interface{}{
	(StopSignal)(0),                      // 0: launchy_proto.StopSignal
	(ProcessState)(0),                    // 1: launchy_proto.ProcessState
	(SystemdAction)(0),                   // 2: launchy_proto.SystemdAction
	(*RestartProcessRequest)(nil),        // 3: launchy_proto.RestartProcessRequest
	(*RestartProcessResponse)(nil),       // 4: launchy_proto.RestartProcessResponse
	(*StopProcessRequest)(nil),           // 5: launchy_proto.StopProcessRequest
	(*StopProcessResponse)(nil),          // 6: launchy_proto.StopProcessResponse
	(*ProcessStatusRequest)(nil),         // 7: launchy_proto.ProcessStatusRequest
	(*ProcessStatusResponse)(nil),        // 8: launchy_proto.ProcessStatusResponse
	(*StartProcessRequest)(nil),          // 9: launchy_proto.StartProcessRequest
	(*StartProcessResponse)(nil),         // 10: launchy_proto.StartProcessResponse
	(*StopLaunchyRequest)(nil),           // 11: launchy_proto.StopLaunchyRequest
	(*StopLaunchyResponse)(nil),          // 12: launchy_proto.StopLaunchyResponse
	(*PingRequest)(nil),                  // 13: launchy_proto.PingRequest
	(*PingResponse)(nil),                 // 14: launchy_proto.PingResponse
	(*ListSystemdServicesRequest)(nil),   // 15: launchy_proto.ListSystemdServicesRequest
	(*ListSystemdServicesResponse)(nil),  // 16: launchy_proto.ListSystemdServicesResponse
	(*SystemdUnitInfo)(nil),              // 17: launchy_proto.SystemdUnitInfo
	(*SystemdServiceActionRequest)(nil),  // 18: launchy_proto.SystemdServiceActionRequest
	(*SystemdServiceActionResponse)(nil), // 19: launchy_proto.SystemdServiceActionResponse
}
var file_launchy_proto_depIdxs = []int32{
	0,  // 0: launchy_proto.RestartProcessRequest.signal:type_name -> launchy_proto.StopSignal
	0,  // 1: launchy_proto.StopProcessRequest.signal:type_name -> launchy_proto.StopSignal
	0,  // 2: launchy_proto.StopLaunchyRequest.stopCommandSignal:type_name -> launchy_proto.StopSignal
	17, // 3: launchy_proto.ListSystemdServicesResponse.services:type_name -> launchy_proto.SystemdUnitInfo
	2,  // 4: launchy_proto.SystemdServiceActionRequest.action:type_name -> launchy_proto.SystemdAction
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_launchy_proto_init() }
func file_launchy_proto_init() {
	if File_launchy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_launchy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestartProcessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launchy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestartProcessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launchy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopProcessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launchy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopProcessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launchy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launchy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launchy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartProcessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launchy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartProcessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launchy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopLaunchyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launchy_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopLaunchyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launchy_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launchy_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launchy_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSystemdServicesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launchy_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSystemdServicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launchy_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemdUnitInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launchy_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemdServiceActionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launchy_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemdServiceActionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_launchy_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_launchy_proto_goTypes,
		DependencyIndexes: file_launchy_proto_depIdxs,
		EnumInfos:         file_launchy_proto_enumTypes,
		MessageInfos:      file_launchy_proto_msgTypes,
	}.Build()
	File_launchy_proto = out.File
	file_launchy_proto_rawDesc = nil
	file_launchy_proto_goTypes = nil
	file_launchy_proto_depIdxs = nil
}
